### ISSUE TITLE
cssClass not working

### ISSUE THREAD

**Issue by gitHubUser151** [okashakhan4141/ngx-intel-telephone-input#2]
Sorry, can't get cssClass to work:

[cssClass]="'test'"

.test{
    background-color: red;
}

Nothing changes.

**Comment by okashakhan4141** [comment]
Is the 'test' class in a global CSS file?

**Comment by gitHubUser151** [comment]
Thank you for the quick reply!
No, css class is in components css file.

I didn't see it mentioned anywhere in readme.
Would be nice to have it local))
